sudo: required

install:
  - sudo bash scripts/install.sh

script:
  - bash scripts/build.sh

deploy:
  provider: s3
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_S3_BUCKET
  skip_cleanup: true
  local_dir: output
  upload-dir: $AWS_S3_UPLOAD_DIR
  region: $AWS_S3_REGION

notifications:
  pushover:
    api_key:
      secure: "Tryjq6+DHeePqvoW5ye8XcQdcktv/+QEySrRuTn5YHr/IU+n++eKAsjNWJQpxeXhWFbrXBvAw+3Zn6qZWBORjdJvuBdz9zkjSKUDTAy8Nru0rCv0w+tFsxFzOvDb8IUph2BBRt+wOWwvIl4VgmFV9yEdH5qKJJJUe5Yphl740fzyl8uhx8+MrUNWFp99HAF9+EetzRV+suNmq6Ij2TBrlFuxGj7Owsi14GBF/BC/ZkV1OK4pf4GcicjQNedZvZwlWyXzO54Zry+7SKR/ohf1CLQp7ikGgp/+NZPSB4+Q6rqP0avULYerOkotAWvn4Z9FVxRW+xB9HvDF+MnuhesuMtOUvNW4WlUELXatrPhADJ0WlirhS/k6uiUwVyl8pDvP6NJdfBEYYNHBnvFhFfjXG0uLuwNIXFhumXIATVn6HnD+Sp9JDAtlRQntI5G0PVogIQQOsOJ8n5PAlx2FYkwtj9QvQY0id7vO4yoWmVGV3O2My9QspoM97vxFMVl2Y3EPOirBdu2jLFYSXvkPymouKEjldHvIhgKr+bb9GydQ9Cyxeehz9F3HiOWnccL9nGT6ZTagVpfgb/yC2c/4g+2nuna/sJrJoi7DPr82TEi/vWBw9anUX1GEktlwZvUtQ2bhTKkec4lj7+TERazS5Hyo1UnkifHgt4iSnBIGXlMvy9k="
    users:
      - secure: "uNF85UbKB6dBVSFPNMtcCxC4IivzQF5TLWS/cFCQP8obyO5Id39cyI5oBuT7/+Je4sz40EJG2fswMGXnDiV8h36/+Yen+12p7mPuOX7mWCUDFhqUDn/ulxTqnCnDi4rsgg0XnzSelpeVwZr2q69cz69nAFqu+lzkab5lgGV+6nqUpvrua5w+jcMs06+iXHygFyzYCjp549Qt7Evx4VFcESRKgLsdOiFAGAloWvB4DB6jFRr4BKM+/dTz0zbSE1gXv11VlrQuHJsLTF+T1XcNguOHojwd3HyVkXkeAtdcCwfyLp4FEXhL763/dlmaSHbO5rW44qI/aoysAniq5P+FV2ofre0MhxYMdEenSeiEEPev5MOMTkNlG9JYzHG4wiBA+H8d3LMMiLhJv7nN1McGAM9ztA5rkPoggDWe4lphqiSY6I+MO1HgbgMEzaVwDQBIfCcqCCFvUSijQ6XmVSk1MYRp4anq5gjsbIABTBgZIcZq3INU7UrBoVqPTROG4UVIP3YIrQIs2mo1WbXHEi4pqj+uozPndvvEJaahRML/aM2xUqg9hzLnXqnYS1be+xtQfPQ7aylwnk1moRuZtCpWza0rpptgByZGKiTD6yDswhlhtDUBHvtjajz4TTzuRWkQdKZ/BDwk2f5UqjVcNU0fVSkAXTWCxxCJhRIGQ3l99a0="
