sudo: required

install:
  - sudo bash scripts/install.sh

script:
  - bash scripts/build.sh

deploy:
  provider: s3
  access_key_id: $AWS_KEY_ID # Use environment variables for security
  secret_access_key: $AWS_SECRET_KEY # Use environment variables for security
  bucket: us-west-2-io-mide-assets # Your S3 bucket
  skip_cleanup: true # Skip cleanup, or Travis will remove your .pdf files
  local_dir: output # The complete contents of this directory will be uploaded
  upload-dir: common/twitter # S3 bucket prefix (directory)
  region: us-west-2 # S3 bucket region (I'm in us-west-2)
