sudo: required

install:
  - sudo bash scripts/install.sh

script:
  - bash scripts/build.sh

deploy:
  provider: s3
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_S3_BUCKET
  skip_cleanup: true
  local_dir: output
  upload-dir: $AWS_S3_UPLOAD_DIR
  region: $AWS_S3_REGION
